import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import PageContainer from "../src/containers/PageContainer"
import Divider from "../src/components/Divider"
import { ButtonElemProps } from "../src/types"

type BtnProps = {
  children: React.ReactNode
  size: "large" | "small"
  color: Pick<React.CSSProperties, "color">
} & ButtonElemProps

const Button = ({
  children,
  size,
  color,
  ...restButtonProps
}: BtnProps): JSX.Element => (
  <button
    style={{
      padding: size === "large" ? "32px" : "8px",
      fontSize: size === "large" ? "32px" : "16px",
      backgroundColor: color,
    }}
    {...restButtonProps}
  >
    {children}
  </button>
)

const DangerButton = ({
  children,
  ...restDangerBtnProps
}: Omit<BtnProps, "color">) => (
  <Button color="red" {...restDangerBtnProps}>
    {children}
  </Button>
)

const Composition: NextPage = () => {
  return (
    <>
      <Head>
        <title>React Patterns | Composition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <h1>Component Composition</h1>
        <h2>Initial custom component</h2>
        <Button size="small" color="blue">
          button
        </Button>
        <Divider />
        <h2>Composed component</h2>
        <DangerButton
          size="large"
          onClick={() => {
            console.log("click")
          }}
        >
          {" "}
          composed button
        </DangerButton>
      </PageContainer>
    </>
  )
}

export default Composition
