import React, { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import PageContainer from "../src/containers/PageContainer"
import UncontrolledForm from "../src/components/UncontrolledForm"
import ControlledForm from "../src/components/ControlledForm"

const ControlledComponents: NextPage = () => {
  const onSubmit = (data: Record<string, any>) => {
    console.log({ data })
  }

  return (
    <>
      <Head>
        <title>React Patterns | Controlled Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <h1>Controlled vs Uncontrolled Components</h1>
        <hr />
        <h2>Uncontrolled Form</h2>
        <UncontrolledForm onSubmit={onSubmit} />
        <hr />
        <h2>Controlled Form</h2>
        <ControlledForm onSubmit={onSubmit} />
      </PageContainer>
    </>
  )
}

export default ControlledComponents
