import React, { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import PageContainer from "../src/containers/PageContainer"

const Container: NextPage = () => {
  return (
    <>
      <Head>
        <title>React Patterns | Container</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <h1>Container</h1>
      </PageContainer>
    </>
  )
}

export default Container
