import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import UserDisplay from '../src/components/UserDisplay';
import ProductDisplay from '../src/components/ProductDisplay';
import CurrentUserLoader from '../src/containers/CurrentUserLoader';
import ResourceLoader from '../src/containers/ResourceLoader';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [formValue, setFormValue] = useState<null | number>(null);
  const [userId, setUserId] = useState<string>('');

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setFormValue(null);
    setUserId(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (userId.trim().length === 0) return;
    const intUserId = parseInt(userId, 10);
    if (typeof intUserId === 'number') {
      setFormValue(parseInt(userId, 10));
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit}>
          <input
            type='text'
            value={userId}
            onChange={handleChange}
            placeholder='type user ID'
          />
          <button type='submit'>submit</button>
        </form>
        <CurrentUserLoader userId={formValue}>
          <UserDisplay />
        </CurrentUserLoader>
        <hr style={{ backgroundColor: '#333', width: '100%' }} />
        <ResourceLoader
          resourceURL={formValue ? `api/users/${formValue}` : null}
          resourceName='user'
        >
          <UserDisplay />
        </ResourceLoader>
        <hr style={{ backgroundColor: '#333', width: '100%' }} />
        <ResourceLoader
          resourceURL={formValue ? `api/products/${formValue}` : null}
          resourceName='product'
        >
          <ProductDisplay />
        </ResourceLoader>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
