import React, { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import PageContainer from "../src/containers/PageContainer"
import withPartiallyApplied from "../src/hoc/withPartiallyApplied"
import { ButtonElemProps } from "../src/types"

type BtnProps = {
  children: React.ReactNode
  size: "large" | "small"
  color: Pick<React.CSSProperties, "color">
} & ButtonElemProps

const Button = ({
  children,
  size,
  color,
  ...restButtonProps
}: BtnProps): JSX.Element => (
  <button
    style={{
      padding: size === "large" ? "32px" : "8px",
      fontSize: size === "large" ? "32px" : "16px",
      backgroundColor: color,
    }}
    {...restButtonProps}
  >
    {children}
  </button>
)

const PartialButton = withPartiallyApplied(Button, { size: "large" })

const Partial: NextPage = () => {
  return (
    <>
      <Head>
        <title>React Patterns | Partial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <h1>Partially-Applied Composition</h1>
        <PartialButton color="green">partial</PartialButton>
      </PageContainer>
    </>
  )
}

export default Partial
