import React, { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import PageContainer from "../src/containers/PageContainer"

const Partial: NextPage = () => {
  return (
    <>
      <Head>
        <title>React Patterns | Partial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <h1>Partially-Applied Composition</h1>
      </PageContainer>
    </>
  )
}

export default Partial
